version: "3.4"

x-project-name:
  &project-name sabacc

x-host:
  &host localhost
x-protocol:
  &protocol http

x-cors:
  &cors "http://localhost:3000"

x-db-host:
  &db-host postgres
x-db-username:
  &db-username postgres
x-db-password:
  &db-password postgres

x-profiles:
  &profiles dev

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: sabacc_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SERVER_HOST: *host
      SERVER_PROTOCOL: *protocol

      SPRING_PROFILES_ACTIVE: *profiles

      #     Database
      SPRING_DATASOURCE_USERNAME: *db-username
      SPRING_DATASOURCE_PASSWORD: *db-password
      SPRING_DATASOURCE_DATABASE_HOST: *db-host
      SPRING_DATASOURCE_DATABASE_PORT: 5432
      SPRING_DATASOURCE_DATABASE_NAME: *project-name

      WEBSOCKET_STOMP_ALLOWED_ORIGIN: *cors

    volumes:
      - ./uploads:/app/uploads

  postgres:
    restart: always
    image: postgres:14.8-alpine3.18
    container_name: sabacc_postgres
    environment:
      POSTGRES_PASSWORD: *db-password
      POSTGRES_USER: *db-username
      POSTGRES_DB: *project-name
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: sabacc_frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine3.19
    container_name: sabacc_nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d