server:
  host: "103.90.75.122:88"

security:
  cors:
    allowed-origin: "${server.protocol}://${server.host}"

websocket:
  stomp:
    allowed-origin: "${server.protocol}://${server.host}"
  game:
    allowed-origin: "${server.protocol}://${server.host}"